#The amount of XP needed for the comparator to output a redstone signal of strength one. By default, the signal will be at full strength if the block has 30 levels stored.
#Range: 0 ~ 143165576
xpForComparator = 93
#Whether the XP Block will pickup any XP orbs around it
pickupXP = true
#The range in blocks around the XP Block in which XP orbs will be picked up
#Range: 0.0 ~ 50.0
pickupRange = 3.0

