#Can the codebreaker be used?
allowCodebreakerItem = true
#Can the admin tool be used?
allowAdminTool = false
#Should mines spawn fire after exploding?
shouldSpawnFire = true
#Should players be able to break a mine without it exploding?
ableToBreakMines = true
#Is the level 1 keycard craftable?
ableToCraftKeycard1 = true
#Is the level 2 keycard craftable?
ableToCraftKeycard2 = true
#Is the level 3 keycard craftable?
ableToCraftKeycard3 = true
#Is the level 4 keycard craftable?
ableToCraftKeycard4 = true
#Is the level 5 keycard craftable?
ableToCraftKeycard5 = true
#Is the limited use keycard craftable?
ableToCraftLUKeycard = true
#Should mines' explosions be smaller than usual.
smallerMineExplosion = false
#Should mines explode if broken while in Creative mode?
mineExplodesWhenInCreative = true
#From how many blocks away can a laser block connect to another laser block?
#Range: > 0
laserBlockRange = 5
#From how many blocks away can an inventory scanner connect to another inventory scanner?
#Range: > 0
inventoryScannerRange = 2
#What is the maximum value that can be set for an alarm's range option? Do note, that this may be limited by chunk loading distance. Higher values may also not be finetuneable.
#Range: > 1
maxAlarmRange = 100
#Allow claiming unowned blocks?
allowBlockClaim = false
#Should the sentry/inventory scanner/laser block/etc. ignore players and entities that are invisible?
respect_invisibility = false
#Should reinforced blocks' textures be slightly darker than their vanilla counterparts?
reinforced_block_tint = true
#Are all mines craftable?
ableToCraftMines = true
#Display owner face on retinal scanner?
retinalScannerFace = true

