
#Server config settings
[server]
	toolSlotsAcceptSwords = true
	disableCrafting = false
	#Enables wearing backpack directly from ground
	enableBackpackBlockWearable = true
	#Enables backpacks spawning in loot chests
	enableLoot = true
	#Backpack immune to any damage source (lava, fire), can't be destroyed, never disappears as floating item
	invulnerableBackpack = true
	#Range: > 250
	tanksCapacity = 4000

